{{- $namespace := .Release.Namespace -}}
{{- $serviceAccount := (lookup "v1" "ServiceAccount" $namespace $namespace ) }}
{{- if .Values.global.enableAuth }}
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: mailrelay-auth-keyvault-secret-provider
spec:
  provider: azure
  parameters:
    {{- if and .Values.useWorkloadIdentity $serviceAccount $serviceAccount.metadata $serviceAccount.metadata.annotations }}
    {{- $clientId := (index $serviceAccount.metadata.annotations "azure.workload.identity/client-id" )}}
    clientID: {{ $clientId }}
    {{- else }}
    usePodIdentity: "{{ .Values.usePodIdentity }}"
    userAssignedIdentityID: "{{ .Values.managedIdentityClientId }}"
    {{- end }}
    keyvaultName: {{ .Values.authKeyVaultName }}-{{ .Values.global.environment }}
    objects: |
      array:
    {{- range $secret := .Values.authKeyVaultSecrets }}
      - |
        objectName: {{ $secret }}
        objectType: secret
    {{- end }}
    tenantId: {{ .Values.tenantId }}
{{- end }}
