{{- if .Values.global.enableAuth }}
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: mailrelay-auth-keyvault-secret-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "{{ .Values.usePodIdentity }}"
    userAssignedIdentityID: "{{ .Values.managedIdentityClientId }}"
    keyvaultName: {{ .Values.authKeyVaultName }}-{{ .Values.global.environment }}
    objects: |
      array:
    {{- range $secret := .Values.authKeyVaultSecrets }}
      - |
        objectName: {{ $secret }}
        objectType: secret
    {{- end }}
    tenantId: {{ .Values.tenantId }}
{{- end }}
