apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: exim-mailrelay-env-secrets-provider
spec:
  provider: azure
    secretObjects:                                 
  - secretName: eximenvsecrets
    type: Opaque
    labels:                                   
      environment: {{ .Values.global.environment }}-secrets
    data: 
    - objectName: relayHost                   
      key: relayhost
  parameters:
    usePodIdentity: "{{ .Values.usePodIdentity }}"
    userAssignedIdentityID: "{{ .Values.managedIdentityClientId }}"
    keyvaultName: {{ .Values.certificate.KeyVault }}
    objects: |
      array:
      - |
        objectName: "relayHost"
        objectType: secret
        objectAlias: relayhost
      - |
        objectName: "relayHostname"
        objectType: secret
        objectAlias: relayhost
      - |
        objectName: "relayFromHosts"
        objectType: secret
        objectAlias: relayfromhosts
      - |
        objectName: "relayToDomains"
        objectType: secret
        objectAlias: relaytodomains

    tenantId: {{ .Values.certificate.tenantId }}

  