apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: exim-mailrelay-env-secrets-provider
spec:
  provider: azure
  secretObjects:                                 
  - secretName: eximenvsecrets
    type: Opaque
    labels:                                   
      environment: {{ .Values.global.environment }}-secrets
    data: 
    - objectName: relayHost                   
      key: relayhost
    - objectName: relayHostname                   
      key: relayhostname
    - objectName: relayFromHosts                   
      key: relayfromhosts
    - objectName: relayToDomains                   
      key: relaytodomains
  parameters:
    usePodIdentity: "{{ .Values.usePodIdentity }}"
    userAssignedIdentityID: "{{ .Values.managedIdentityClientId }}"
    keyvaultName: {{ .Values.authKeyVaultName }}-{{ .Values.global.environment }}
    objects: |
      array:
      - |
        objectName: "relayHost"
        objectType: secret
        objectAlias: relayhost
      - |
        objectName: "relayHostname"
        objectType: secret
        objectAlias: relayhostname
      - |
        objectName: "relayFromHosts"
        objectType: secret
        objectAlias: relayfromhosts
      - |
        objectName: "relayToDomains"
        objectType: secret
        objectAlias: relaytodomains

    tenantId: {{ .Values.certificate.tenantId }}

  