apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: exim-env-secrets-provider
spec:
  provider: azure
  secretObjects:
  - secretName: eximenvsecrets
    type: Opaque
    labels:
      environment: {{ .Values.global.environment }}-secrets
    data:
    - key: relayhost
      objectName: relayHost
    - key: relayhostname
      objectName: relayHostname
    - key: relayfromhosts
      objectName: relayFromHosts
    - key: relaytodomains
      objectName: relayToDomains
  parameters:
    usePodIdentity: "{{ .Values.usePodIdentity }}"
    userAssignedIdentityID: "{{ .Values.managedIdentityClientId }}"
    keyvaultName: {{ .Values.authKeyVaultName }}-{{ .Values.global.environment }}
    objects: |
      array:
      - |
        objectName: relayHost
        objectType: secret
      - |
        objectName: relayHostname
        objectType: secret
      - |
        objectName: relayFromHosts
        objectType: secret
      - |
        objectName: relayToDomains
        objectType: secret
    tenantId: {{ .Values.certificate.tenantId }}

