apiVersion: v1
kind: Service
metadata:
  name: {{ template "exim.fullname" . }}-exporter
  labels:
    app: {{ template "exim.name" . }}
    chart: {{ template "exim.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.eximExporterService.type }}
  ports:
    - port: {{ .Values.eximExporterService.port }}
      targetPort: eximexporter
      name: eximexporter
      {{ if and (eq .Values.eximExporterService.type "NodePort") (.Values.eximExporterService.nodePort) }}
      nodePort: {{ .Values.eximExporterService.nodePort }}
      {{ end }}
  selector:
    app: {{ template "exim.name" . }}
    release: {{ .Release.Name }}
