apiVersion: v1
kind: Service
metadata:
  name: {{ template "exim.fullname" . }}
  labels:
    app: {{ template "exim.name" . }}
    chart: {{ template "exim.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.eximexporter-service.port }}
      targetPort: eximexporter-port
      name: eximexporter-port
      {{ if and (eq .Values.eximexporter-service.type "NodePort") (.Values.eximexporter-service.nodePort) }}
      nodePort: {{ .Values.service.nodePort }}
      {{ end }}
  selector:
    app: {{ template "exim.name" . }}
    release: {{ .Release.Name }}
