{{- if .Values.global.enableAuth }}
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: mailrelay-inbound-keyvault-certificate-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "{{ .Values.usePodIdentity }}"
    userAssignedIdentityID: "{{ .Values.managedIdentityClientId }}"
    keyvaultName: {{ .Values.certificate.KeyVault }}
    objects: |
      array:
      - |
        objectName: {{ .Values.certificate.inboundCert.objectName }}
        objectAlias: {{ .Values.certificate.inboundCert.name }}.{{ .Values.certificate.serverName }}.crt
        objectType: cert
      - |
        objectName: {{ .Values.certificate.inboundCert.objectName }}
        objectAlias: {{ .Values.certificate.inboundCert.name }}.{{ .Values.certificate.serverName }}.key
        objectType: key
    tenantId: {{ .Values.certificate.tenantId }}
{{- end }}
