apiVersion: v1
kind: Secret
metadata:
  name: {{ template "exim.fullname" . }}
  labels:
    app: {{ template "exim.name" . }}
    chart: {{ template "exim.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:  
  SMTP_PASSWORD: {{ if .Values.smtp.relayPassword }}{{ .Values.smtp.relayPassword | b64enc }}{{ else }}""{{ end }}